# Generated by Django 4.2.11 on 2024-05-30 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('a_lname', models.CharField(max_length=5)),
                ('a_fname', models.CharField(max_length=20)),
                ('acc', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('passwd', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'administrator',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('ba_lname', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('ba_fname', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'book_author',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('phone', models.IntegerField(unique=True)),
                ('m_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ssn', models.CharField(max_length=10, unique=True)),
                ('m_lname', models.CharField(max_length=5)),
                ('m_fname', models.CharField(max_length=20)),
                ('sex', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MembersBook',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=25)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('author_lname', models.CharField(max_length=5)),
                ('author_fname', models.CharField(max_length=20)),
                ('publisher', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'members_book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('addr', models.CharField(max_length=40, unique=True)),
                ('s_id', models.IntegerField(primary_key=True, serialize=False)),
                ('s_name', models.CharField(max_length=10)),
                ('s_statu', models.IntegerField()),
            ],
            options={
                'db_table': 'station',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('v_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'visitor',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='Mb',
            fields=[
                ('mm', models.OneToOneField(db_column='Mm_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='members.member')),
            ],
            options={
                'db_table': 'mb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ms',
            fields=[
                ('mm', models.OneToOneField(db_column='Mm_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='members.member')),
            ],
            options={
                'db_table': 'ms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vb',
            fields=[
                ('vv', models.OneToOneField(db_column='Vv_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='members.visitor')),
            ],
            options={
                'db_table': 'vb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vs',
            fields=[
                ('vv', models.OneToOneField(db_column='Vv_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='members.visitor')),
            ],
            options={
                'db_table': 'vs',
                'managed': False,
            },
        ),
    ]
