# Generated by Django 4.2.11 on 2024-05-30 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_administrator_authgroup_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
    ]
