# Generated by Django 5.0.6 on 2024-06-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_author_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='出版社名稱'),
        ),
    ]
