# Generated by Django 5.0.6 on 2024-06-05 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_book_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrator',
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='BookAuthor',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.RemoveField(
            model_name='mb',
            name='mm',
        ),
        migrations.RemoveField(
            model_name='ms',
            name='mm',
        ),
        migrations.DeleteModel(
            name='MembersBook',
        ),
        migrations.DeleteModel(
            name='Station',
        ),
        migrations.RemoveField(
            model_name='vb',
            name='vv',
        ),
        migrations.RemoveField(
            model_name='vs',
            name='vv',
        ),
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
        migrations.DeleteModel(
            name='Mb',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Ms',
        ),
        migrations.DeleteModel(
            name='Vb',
        ),
        migrations.DeleteModel(
            name='Visitor',
        ),
        migrations.DeleteModel(
            name='Vs',
        ),
    ]
