# Generated by Django 5.0.6 on 2024-06-05 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_publisher_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='members.member', verbose_name='會員'),
        ),
        migrations.AlterField(
            model_name='book',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='members.station', verbose_name='站點'),
        ),
    ]
